config/routes.rb
Rails.application.routes.draw do
 devise_for :users
root 'public_recipes#index'

  resources :recipes, only: [:index, :show, :create, :new, :destroy] do
    resources :recipe_foods, except: :update
  end

  resources :recipes do
    member do
      patch 'toggle_visibility'
    end
  end

  resources :foods, only: [:index, :show, :create, :new, :destroy] 
  resources :shopping_lists, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Recipe, public: true

    return unless user.present?

    can :manage, Recipe, user_id: user.id
    can :manage, RecipeFood, user_id: user.id
    can :manage, Food, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true, length: { in: 1..15 }
  validates :measurement_unit, presence: true, length: { in: 1..9 }
  validates :price, numericality: { only_integer: true, greater_than: 0 }
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, length: { in: 1..18 }
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :description, presence: true, length: { in: 1..450 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :food, uniqueness: { scope: :recipe, message: 'already exists in this recipe' }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods
  has_many :recipes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  def index
    @foods = current_user.foods
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user

    if @food.save
      flash[:success] = 'Food succesfully added'
      redirect_to foods_path
    else
      flash[:error] = 'Error: Food could not be added'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    flash[:notice] = 'You deleted food successfully'
    redirect_back(fallback_location: root_path)
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.all.where(public: true).includes([:user])
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = params[:recipe_id]
    if @recipe_food.save
      flash[:success] = 'Recipe Food succesfully added'
      redirect_to recipe_path(params[:recipe_id])
    else
      flash[:error] = 'Error: Recipe Food could not be added'
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @food = @recipe.foods.find(params[:id])
    @recipe_food = RecipeFood.find_by(food_id: @food.id)
    @recipe_food.destroy
    flash[:notice] = 'Ingredient removed successfully'
    redirect_back(fallback_location: root_path)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe.id), notice: 'Visibility updated successfully.'
    else
      render :edit
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      flash[:success] = 'Recipe succesfully added'
      redirect_to recipes_path
    else
      flash[:error] = 'Error: Recipe could not be added'
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'You deleted Recipe successfully'
    redirect_back(fallback_location: root_path)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  def index
    @current_user = current_user
    @foods = []
    @total_price = 0
    flag = true
    current_user.recipes.includes([:foods]).each do |recipe|
      recipe.foods.each do |food|
        q = RecipeFood.find_by(food_id: food.id).quantity
        f = current_user.foods.find(food.id)
        flag = check_duplicate(@foods, f, q)
        if (f.quantity - q).negative? && flag
          @foods << { name: f.name, quantity: f.quantity - q, price: f.price * (f.quantity - q) }
        end
      end
    end
    @foods.each { |f| @total_price += f[:price] }
    @foods
  end

  def check_duplicate(foods, food, quantity)
    foods.each do |food_item|
      next unless food_item[:name] == food.name

      food_item[:quantity] = food_item[:quantity] - quantity
      food_item[:price] = food_item[:quantity] * food.price
      return false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/foods/index.html.erb
<%= render '/shared/navbar'%>
<div class="container mt-4">
  <div class="d-flex justify-content-end mb-3">
    <%= link_to 'Add Food', new_food_path, class: 'btn btn-primary' %>
  </div>
  <table class="table table-striped">
    <thead class="bg-primary text-white">
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Measurement Unit</th>
        <th scope="col">Price</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.quantity.to_i %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= "$#{food.price.to_i}" %></td>
          <td>
            <%= button_to "Delete", food_path(food.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<div>
<%= render '/shared/navbar'%>
</div>

<h3 style='text-align: center; margin-top: 20px;'>Add new food here <h3>

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with model: @food do |form| %>
        <div class="form-group">
          <%= form.label :name, "Food Name" %>
          <%= form.text_field :name, placeholder: "Enter Food name", class: "form-control mb-3 mt-1" %>
        </div>
        <div class="form-group">
          <%= form.label :measurement_unit, "Measurement Unit" %>
          <%= form.select :measurement_unit, [["grams"], ["kilos"], ["liters"], ["milliliters"]], {}, class: "form-control mb-3 mt-1" %>
        </div>
        <div class="form-group">
          <%= form.label :price, "Price" %>
          <%= form.number_field :price, placeholder: "Enter Your Price", class: "form-control mb-3 mt-1" %>
        </div>
        <div class="form-group">
          <%= form.label :quantity, "Quantity" %>
          <%= form.number_field :quantity, placeholder: "Enter Your Quantity", class: "form-control mb-3 mt-1" %>
        </div>
        <div class="form-group">
          <%= form.submit "Add New Food", class: "btn btn-primary mt-4" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App Diary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <footer class='footer'> <p>Built by Muda and Kevin</p> </footer>
  </body>
</html>

app/views/public_recipes/index.html.erb
<%= render '/shared/navbar'%>
<h1 style="text-align: center; margin-top: 50px;">Public Recipes</h1>
<div class = 'container'>
<% @recipes.each do |recipe|%>
<div style="font-weight: bold; --bs-bg-opacity: .25;"  class = 'shadow p-3 mb-5 bg-body-tertiary rounded bg-primary p-2 recipe_container border border-dark p-4 m-2 d-flex justify-content-between'>
<div class = 'recipe_heading'>
<h2><%= link_to recipe.name, recipe_path(recipe.id) %></h2>
<div class = 'btn_recipe_remove'>
<h4><%= "By: #{recipe.user.name}" %></h4>
</div>
</div>
<div class = 'recipe_text pr-3'>

 <h4><%= "Total Food Items: #{recipe.foods.size}" %></h4>
<h4><%= "Total Price: #{recipe.foods.all.sum(:price)}" %></h4> 
</div>
</div>
<%end%>


</div>

app/views/recipe_foods/new.html.erb
<%= render '/shared/navbar'%>
<h2 style='text-align: center; margin-top: 20px;'>Add Ingredients</h2>
<div class="add_new_ingredient"  style='display: flex; justify-content: center; align-items: center;'>
  <%= form_with model: @recipe_food, url: recipe_recipe_foods_path(params[:recipe_id]), method: :post, local: true do |form| %>
    <div class="form-group">
      <%= form.label :food_id %>
      <%= form.select :food_id, current_user.foods.all.map { |food| [food.name, food.id] }, {}, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :quantity %>
      <%= form.number_field :quantity, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.submit "Add", class: "btn btn-primary mt-4" %>
    </div>
  <% end %>
</div>

app/views/recipes/index.html.erb
<div class='top-bar'> <h1><%="Welcome #{current_user.name} to your Recipes"%></h1> </div>
<%= render '/shared/navbar'%>
<div class="container"style="width: 800px; margin-top: 20px;">
<% @recipes.each do |recipe| %>
  <div class="card mb-3">
    <div class="card-header d-flex justify-content-between align-items-center">
      <%= link_to recipe.name, recipe_path(recipe.id) %>
      
    </div>
    <div class="row g-0">
      <div class="col-md-8">
        <div class="card-body">
        <% if current_user.present? && can?(:destroy, recipe) %>
        <%= button_to "Remove", recipe_path(recipe.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger btn-sm ml-2' %>
      <% end %>
          
        </div>
      </div>
      <div class="col-md-4 d-flex align-items-center justify-content-center">
        <p class="card-text" style="margin-right: 10px;"><%= recipe.description %></p>
      </div>
    </div>
  </div>
<% end %>

  <button class="btn_add_recipe btn btn-primary">
    <%= link_to 'Add Recipe', new_recipe_path, class: "text-white" %>
  </button>
</div>

app/views/recipes/new.html.erb
<div>
<%= render '/shared/navbar'%>
</div>

<div class="container mt-4">
  <div class="new_recipe">
    <h2 style='text-align: center; margin-top: 20px;'>Create New Recipe</h2>
    <div class="back_to_recipe" style='display: flex; justify-content: center; align-items: center;'>
      <%= link_to 'Back to Recipes', recipes_path %>
    </div>
    <div class="add_new_recipe">
      <%= form_with model: @recipe do |form| %>
        <div class="form-group">
          <%= form.label :name %>
          <div class="new_recipe_name">
            <%= form.text_field :name, class: "form-control mb-3 mt-1" %>
          </div>
        </div>
        <div class="form-group">
          <%= form.label :preparation_time %>
          <div class="recipe_prep_time">
            <%= form.number_field :preparation_time, class: "form-control mb-3 mt-1" %>
          </div>
        </div>
        <div class="form-group">
          <%= form.label :cooking_time %>
          <div class="cooking_time">
            <%= form.number_field :cooking_time, class: "form-control mb-3 mt-1" %>
          </div>
        </div>
        <div class="form-group">
          <%= form.label :description %>
          <div class="description">
            <%= form.text_area :description, class: "form-control mb-3 mt-1" %>
          </div>
        </div>
        <div class="form-group">
          <%= form.label :public %>
          <div class="public mb-3 mt-1">
            <%= form.select :public, options_for_select([[ 'Yes', true ], [ 'No', false ]]), class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= form.submit class: "btn btn-primary mt-4" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<%= render '/shared/navbar'%>
<div class="container">
  <div class="upper_section">
    <div class="recipe_heading text-center">
      <h2><%=@recipe.name %></h2>
    </div>
    <div class="recipe_details">
      <div class="d-flex justify-content-between align-items-center">
        <p class="m-0"><%= "Preparation Time: #{@recipe.preparation_time} hour"%></p>
         <% if !current_user.nil? && current_user.id == @recipe.user_id %>
        <%= form_for @recipe do |f| %>
          <div class="custom-control custom-switch">
            <%= f.check_box :public, id: "visibility-toggle", class: "custom-control-input" %>
            <%= f.label :public, class: "custom-control-label", for: "visibility-toggle" %>
          </div>
          
          <%= f.submit "Update Visibility", class: "btn btn-primary" %>
          <%end%>
        <% end %>
      </div>
      <p><%= "Cooking Time: #{@recipe.cooking_time} hour"%></p>
      <p><%= "Steps to prepare: #{@recipe.description}"%></p>
    </div>
  </div>
   <% if !current_user.nil? && current_user.id == @recipe.user_id %>
<div class="buttons mt-5" style='display:flex; justify-content: space-between;'>
  <%= link_to 'Generate Shopping List', shopping_lists_path, class: 'btn btn-primary mr-2' %>
  <%= link_to 'Add Ingredient', new_recipe_recipe_food_path(@recipe.id), class: 'btn btn-primary' %>
</div>
<%end%>
  <div class="table">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @recipe.foods.each do  |food| %>
          <tr>
            <td><%= food.name %></td>
            <%@quantity = RecipeFood.find_by(food_id: food.id).quantity%>
            <td><%= @quantity %></td>
            <td><%= "$ #{food.price * @quantity}" %></td>
            <% if !current_user.nil? && current_user.id == @recipe.user_id %>
              <td><%= button_to "remove", recipe_recipe_food_path(@recipe.id, food.id), method: :delete, class:'btn btn-danger' %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class = 'top-bar'>
<div class="navbar navbar-expand-lg navbar-light bg-light">
  <% if current_user.present? %>
    <h5 class="navbar-brand">Welcome, <%= current_user.name %></h5>
    <div class="ml-auto">
      <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger' %>
    </div>
  <% else %>
    <div class="ml-auto">
      <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary mr-2' %>
      <%= link_to 'Sign-up', new_user_registration_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>
</div>

<div class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-nav mx-auto">
    <%= link_to 'Home', root_path, class: 'nav-link' %>
    <%= link_to 'Food List', foods_path, class: 'nav-link' %>
    <%= link_to 'Recipes List', recipes_path, class: 'nav-link' %>
    <%= link_to 'Shopping List', shopping_lists_path, class: 'nav-link' %>
  </div>
</div>

app/views/shopping_lists/index.html.erb
<div>
<%= render '/shared/navbar'%>
</div>

<h1 class='text-center' style="margin-bottom: 30px;">Shopping list </h1>
<div style="display: flex; justify-content: space-around; margin-bottom: 40px;">
    <h4>Amount of food items to buy: <span><%= @foods.length %></span> </h4>
    <h4>Total value of food needed: <span>$<%= @total_price * -1 %> </span></h4>
</div>

<div class="mt-2">
  <% if @foods.length.zero? %>
    <h3 class="text-2xl font-bold text-center text-indigo-600">
      You have everything needed to make that recipe!
    </h3>
  <% else %>
    <table class="table table-striped mx-auto" style="width: 500px;">
      <thead class="bg-primary text-white">
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Total Price</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |f| %>
          <tr>
            <td><%= f[:name] %></td>
            <td><%= f[:quantity] * -1 %></td>
            <td>$<%= f[:price] * -1 %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>